### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by felsspat** [salvoilmiosi/bomberman#1]
Hi, 

I would like to make a simple bomberman game in HTML5. I probably won't ever finish it, and if I should finish it, it will be free. I didn't find a licence file in your repo, may I use your graphics? I would use players.png, tileset_1.png and explosions.png.

**Comment by salvoilmiosi** [comment]
yes, you can. I actually just googled "super bomberman tileset" and found
that SNES etc .png file (it could be copyrighted probably)

2016-10-14 19:53 GMT+02:00 felsspat notifications@github.com:
